### ISSUE TITLE
Создай страничку

### ISSUE THREAD

**Issue by igorlukanin** [Tank090493/Test-pilot#1]
Делай страничку в «[индексном файле](https://www.jino.ru/help/faq/filemanagement/index-file/)».

Пусть для начала на ней будут:
* фотография
* имя
* контактные данные

**Comment by igorlukanin** [comment]
Вопрос: для чего именно ты указала стиль в этом фрагменте — `<p style="color: black;">`? Что будет, если убрать этот стиль?

Что такое `Space`? Дай странице осмысленное название.

**Comment by Tank090493** [comment]
Так. Ответ на первый вопрос: указала стиль в рамках обучения. Если убрать этот стиль - ничего не изменится; если выбрать другой цвет(rad, green и т.д.), то текст, который внутри этих тегов поменяет цвет.
Space - это космос, космическая сфера.. Вполне осмысленно название

**Comment by igorlukanin** [comment]
1. Старайся не делать ничего «в рамках обучения» :) Делай только то, что нужно, чтобы выполнить задание. Например, сейчас ты «выстрелила себе в ногу» и вот почему.

Считается вредной практикой указывать только цвет текста на странице или только цвет фона на странице, потому что в некоторых браузера на некоторых операционных системах цвет фона по умолчанию (который ты не указала) может быть другой. Не гарантируется, что цвет фона по умолчанию всегда белый, а цвет текста по умолчанию всегда чёрный. Можно рассчитывать, что они по умолчанию довольно контрастные и различаются, но гарантий нет. Поэтому, всегда лучше задавать цвет фона и цвет текста в стилях в явном виде. Или если ты задаёшь один параметр (как сейчас), то обязательно задавать и второй.

Давай сделаем так: удали стиль у абзаца, а потом задай цвет фона и цвет текста для всей страницы с помощью тега `style`.

2. Какой ещё космос? Я думал, это твоя персональная страничка :)

**Comment by igorlukanin** [comment]
Принято 👍.
