### ISSUE TITLE
Опубликуй страницу в интернете

### ISSUE THREAD

**Issue by igorlukanin** [Tank090493/Test-pilot#2]
Github умеет публиковать простые статичные сайты — такие, как твоя страница, и чуть более сложные. Называется такая функция [Github Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

Почитай и опубликуй сайт. Укажи эту ссылку в описании репозитория на [этой странице](https://github.com/Tank090493/Pilot-tester).

**Comment by igorlukanin** [comment]
Вот пример. Обрати внимание, что ссылка указана в специальном поле для ссылки, а не в названии репозитория.

<img width="1080" alt="screen shot 2017-06-15 at 08 33 26" src="https://user-images.githubusercontent.com/3852894/27164263-81450540-51a5-11e7-867d-14585f54ec44.png">

**Comment by igorlukanin** [comment]
А название репозитория лучше верни обратно, оно ж неплохое было :) Можешь даже более грамотную версию из нашего обсуждения в Телеграме использовать. (Да, нужно будет поискать в Телеграме — это я намекаю, что если писать относящееся к задачкам здесь в комментариях, чего ты сторонишься, то искать там будет не нужно.)

**Comment by igorlukanin** [comment]
Ещё одна подсказка:

<img width="1066" alt="screen shot 2017-06-16 at 13 25 35" src="https://user-images.githubusercontent.com/3852894/27218424-8234fc2e-5297-11e7-8666-cb8f6b648c4a.png">

**Comment by Tank090493** [comment]
Сделано !

**Comment by igorlukanin** [comment]
Принято 👍.
