### ISSUE TITLE
Добавь биографию и контактные данные

### ISSUE THREAD

**Issue by igorlukanin** [Tank090493/Test-pilot#3]
Расскажи кратко о своей биографии и укажи, как с тобой можно связаться: по телефону, по емейлу, через соцсети и мессенжеры.

Вероятно, тебе будут полезны списки (`ul`, `li`) и ссылки (`a`). Обрати внимание на атрибут `target` у ссылок, а также на «схему» в адресах ссылок — нужно сделать так, чтобы клик по ссылке, ведущей на другой сайт, не уводил пользователя с твоей странице, а клик по ссылке на аккаунт в мессенжере (например, Телеграме) открывали сразу этот мессенжер, а клик по телефону — звонил по этому телефону.

Информацию погугли, найти очень легко.

**Comment by Tank090493** [comment]
Что-то тяжко биографию написать) я далеко не писатель:) ахах

**Comment by Tank090493** [comment]
Сделано!

**Comment by igorlukanin** [comment]
Отлично. Ссылки на аккаунты в мессенжерах работают, это хорошо.

А давай теперь ты:

1. Перечитаешь и выполнишь часть задания, которая касается атрибута `target` у ссылок. Я не зря об этом писал. Зачем писать «Сделано!», если это не сделано?

2. Исправишь опечатки, добавишь пробелы и знаки препинания там, где их не хватает, и уберёшь там, где они не нужны.

3. Вместо знаков `"`, которые обозначают единицу измерения «минута», будешь использовать знаки кавычек-ёлочек, подходящие для текстов на русском языке. Вместо дефисов с пробелами с двух сторон — длинные тире. Читай про [кавычки](https://www.artlebedev.ru/kovodstvo/sections/104/) и [типографику](https://www.artlebedev.ru/kovodstvo/sections/62/).

4. Напишешь название компаний без ошибок.

5. Исправишь ошибку в адресе эл. почты и названии мессенжера, сделанного Павлом Дуровым.

6. Откажешься от использования тега `br` — он только засоряет твою HTML-разметку — и разделишь текст на абзацы.

7. Откажется от «псевдозаголовков», сделанных с помощью тегов `p` и `strong`. Используй для заголовков теги `h*`.

**Comment by igorlukanin** [comment]
https://github.com/Tank090493/Test-pilot/commit/7fb9e5f1dae8abed428cb2a17dbd575336c057f8 — вот эти изменения довольно сомнительные. Ты добавила несколько списков с одним элементом внутри. Это как поставить в квартире несколько шкафов и поставить в каждый по одной книге.

**Comment by igorlukanin** [comment]
Да, поясни ещё, зачем у некоторых ссылок `ref="nofollow"`.

**Comment by Tank090493** [comment]
Посмотри сейчас, пожалуйста

**Comment by igorlukanin** [comment]
1. Ок
2. Ок, но осталась одна точка, после которой нет пробела
3. Ок
4. Ок, а что насчёт названия текущей компании? Смотри, как она [сама о себе пишет](http://www.apress.ru/o-kompanii/).
5. Ок, но что насчёт мессенжера Дурова?
6. Ок
7. Ок, но почему у тебя есть теги `h2` и `h3`, но нет `h1`?
8. Что с [этим комментарием](https://github.com/Tank090493/Test-pilot/issues/3#issuecomment-310896264)? Ты используешь списки неправильно. Сделай один список.
9. Что с [этим комментарием](https://github.com/Tank090493/Test-pilot/issues/3#issuecomment-310897120)?

**Comment by Tank090493** [comment]
2. Сделано
4. Сделано
5. Сделано
7. Потому мне не нравится то, что тэг h1 такой огромный
8. Исправила
9. Подглядела на https://ludwig.timepad.ru/event/502734/

**Comment by igorlukanin** [comment]
2. Вот точка, после которой нет пробела:
<img width="229" alt="screen shot 2017-06-29 at 14 59 31" src="https://user-images.githubusercontent.com/3852894/27682348-a1a38c58-5cdb-11e7-981b-e83d3f7cfb98.png">

4. АБАК-ПРЕСС [везде](http://www.apress.ru/o-kompanii/), где я [смог найти](https://focus.kontur.ru/entity?query=1126685016039), пишет о себе БОЛЬШИМИ БУКВАМИ. Может, и тебе так надо? Как правильно? В каких источниках написано маленькими?

5. «Телеграмм» или «Телеграм»? Покажи мне хоть один источник, где пишется с двумя «м» :)

7. Не нравится — используй CSS, чтобы исправить оформление. Привыкай, что теги нужно выбирать и использовать по смыслу, а не по их внешнему виду. Если внешний вид не нравится — пиши CSS-правило. В данном случае, замени `h2` → `h1`, `h3` — `h2`, а потом используй CSS-свойство `font-size`, чтобы исправить размер шрифта.

8. Отлично, список (`ul`) теперь один, только внутри него не элементы списка (`li`), а абзацы (`p`). Теперь избавляйся от абзацев :) Должно быть примерно так:
```html
<ul>
  <li>...</li>
  <li>...</li>
  ...
</ul>
```

9. Причём тут Быстроновский или Таймпад и ссылки с `ref="nofollow"`? :) Ты не хочешь, чтобы сайты, на которые ты ссылаешься, получали больший вес от поисковой системы, потому что на них ссылается твой очень классный сайт? Не будет этого, потому что твой сайт не очень классный :) А значит, ты просто засоряешь свой код ненужной фигнёй. Лучше убери.

**Comment by igorlukanin** [comment]
Кстати, прикольно, что в описании коммита указала, что он к этому заданию относится.

**Comment by Tank090493** [comment]
пункт 9. я же убрала, зачем ты мне пишешь, чтобы я это убрала? оч странно

**Comment by igorlukanin** [comment]
Не заметил, что уже убрала. Ок!

**Comment by Tank090493** [comment]
7. Я сделала с абзацами, потому что мне не нравится что слииииишком мало отступа между мессенджерами ..

**Comment by igorlukanin** [comment]
Для этого есть CSS-свойство `margin`. Как я уже писал выше, теги нужно применять по смыслу, а не по внешнем виду.

**Comment by Tank090493** [comment]
Игорь, так?

![screenshot_1](https://user-images.githubusercontent.com/27670568/27685693-c6cf8e7a-5ce8-11e7-953e-66b380317bdd.png)

**Comment by igorlukanin** [comment]
А пункт 7?

**Comment by Tank090493** [comment]
См. скрин.

**Comment by igorlukanin** [comment]
Внутри тега «список» (`ul`) должны сразу идти теги «элемент списка» (`li`).

Сейчас у тебя «ссылкой» как бы является элемент списка и всё, что в нём находится. А надо вложить ссылку в элемент списка.

**Comment by Tank090493** [comment]
Закроешь эту задачку?

**Comment by igorlukanin** [comment]
Принято 👍.
