### ISSUE TITLE
Добавь фавиконку

### ISSUE THREAD

**Issue by igorlukanin** [Tank090493/Test-pilot#4]
Вот что это такое: https://ru.wikipedia.org/wiki/Favicon

**Comment by Tank090493** [comment]
Сделала это задание, проверь, пожалуйста.  Остальные в процессе у меня)

**Comment by igorlukanin** [comment]
Всё почти хорошо. Можно сделать ещё лучше — поменять формат картинки.

Сейчас твоя картинка в формате JPEG — он хорошо подходит для больших фотографий, но делать в нём микроскопические иконки — не самая лучшая затея. В том числе потому, что JPEG — формат со сжатием с потерями, а значит, при сохранении в нём часть информации об изображении теряется. Для фотографий это нормально, для иконок — нет.

Используй лучше формат PNG, тем более, что он поддерживается всеми нужными браузерами: http://caniuse.com/#feat=link-icon-png

Чтобы поменять формат иконки, используй MS Paint или установи на компьютер Paint.NET. Проверь и напиши сюда, как изменится размер иконки с изображением (в байтах) после смены формата.

**Comment by Tank090493** [comment]
О Божээээ, Игорь)

**Comment by Tank090493** [comment]
![1](https://user-images.githubusercontent.com/27670568/27334742-b0792b88-55e3-11e7-9d2d-6affc565abfd.png)
![default](https://user-images.githubusercontent.com/27670568/27334741-b073c2f6-55e3-11e7-97a4-cdf1553ff703.png)

Так?

**Comment by igorlukanin** [comment]
Если увеличить твою иконку с петушком в формате JPEG, то можно увидеть, что части изображения, которые на глаз кажутся заполненными белыми (или светлыми) пикселями, на самом деле очень «шумные»:

![screen shot 2017-06-25 at 16 04 31](https://user-images.githubusercontent.com/3852894/27515595-6e6586b6-59c0-11e7-94e2-71acfea8693d.png)

Поэтому при сохранении в формате PNG мы не получаем большого выигрыша в размере — каждый пиксель изображения имеет уникальный цвет. Из-за этого эффективно сжать изображение не получается.

![screen shot 2017-06-25 at 16 04 42](https://user-images.githubusercontent.com/3852894/27515611-d3180dd6-59c0-11e7-8650-eff2272e17eb.png)

Если просто сделать прозрачными области со светлыми пикселями...

![screen shot 2017-06-25 at 16 05 57](https://user-images.githubusercontent.com/3852894/27515612-daf9edda-59c0-11e7-8da5-e5fe403b390c.png)

...то размер изображения сразу уменьшается — эти области залиты одним и тем же цветом (прозрачным) и они хорошо сжимаются:

![screen shot 2017-06-25 at 16 06 03](https://user-images.githubusercontent.com/3852894/27515613-f30ef12c-59c0-11e7-862a-f4673ed266dd.png)

1. Почитай про [различия между PNG и JPEG](https://www.google.ru/search?client=safari&rls=en&q=png+vs+jpeg&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=tZlPWZ2cJ87D7gTxkZigBw).

2. Поменяй фавиконку на другую — в формате PNG. Не конвертируй её из JPEG. Проверь, чтобы однородные области иконки не были заполнены «шумом» от JPEG-сжатия.

3. Запомни, что JPEG — только для фотографий и похожий на них изображений. Для других случаев — PNG. Для анимированных картинок — GIF.

**Comment by Tank090493** [comment]
Изменила на новую фавикоку. Проверь, пожалуйста)

**Comment by igorlukanin** [comment]
Принято 👍.
