### ISSUE TITLE
Научись пользоваться pull request-ами

### ISSUE THREAD

**Issue by igorlukanin** [Tank090493/Test-pilot#7]
https://github.com/Tank090493/Test-pilot/commit/04ebf615acde2ce7db8202dbced6538c41124954 — в этом коммите, озаглавленном «Добавление новой фавиконки», ты не только поменяла фавиконку, но сделала кучу изменений, которые к этому не относятся.

Так делать нехорошо:

1. Это вводит в заблуждение других разработчиков, которые будут пытаться по истории коммитов разобраться, как менялся код.
2. Это не позволяет выделить изменения, которые были нужны, чтобы закрыть одну задачу — получается, что в одном коммите смешаны изменения, которые нужны для разных задач.
3. Это не позволяет начать делать одну задачу (сделать несколько коммитов), отвлечься на другую (снова сделать несколько коммитов), а потом вернуться к первой — изменения от разных задач смешаются в коде.

Поэтому, отныне поступай так:

1. Никогда не сохраняй в одном коммите разные изменения, относящиеся к разным задачам (или разным подзадачам в рамках задачи). Делай небольшие, логичные, обособленные коммиты.
2. Прочитай про [пулл-реквесты](https://git-scm.com/book/ru/v2/GitHub-Внесение-собственного-вклада-в-проекты) — и [ещё тут](http://www.unix-lab.org/posts/pull-request/) — и все будущие задачки решай только с их помощью: для каждой задачи заводишь ветку, делаешь в эту ветку один или несколько коммитов, заводишь пулл-реквест.

**Comment by igorlukanin** [comment]
Чтобы выполнить это задание — сделай пулл-реквест :)

**Comment by Tank090493** [comment]
хэй, я думала надо делать задания по порядочку

**Comment by igorlukanin** [comment]
Делай как хочешь :)

**Comment by igorlukanin** [comment]
Стало понятно, почему я не получил уведомление на почту — тут ты ничего не написала, а в пулл-реквесте (https://github.com/Tank090493/Test-pilot/pull/8) не назначила reviewer-а или assignee:

<img width="398" alt="screen shot 2017-07-02 at 16 40 36" src="https://user-images.githubusercontent.com/3852894/27769527-3a841314-5f45-11e7-8102-c6eaac3f6a24.png">

Сам реквест нормальный, разве что хорошим тоном было бы написать что-нибудь в его описании.

Обрати внимание, что изменения по всем коммитам в рамках реквеста (или ветки) можно смотреть здесь: https://github.com/Tank090493/Test-pilot/pull/8/files. Очень удобно.

Так что сначала назначь меня reviewer-ом, я «отревьюю», потом примешь реквест — тебе должна быть видна кнопка со значением «Смерджить ветки и закрыть пулл-реквест».

**Comment by Tank090493** [comment]
Готово!

**Comment by igorlukanin** [comment]
Отлично 👍.
